config:
  validation: true
  warningsAsErrors: true

naming:
  FunctionNaming:
    functionPattern: '[A-Za-z][a-zA-Z0-9]*'
  MatchingDeclarationName:
    active: false
  MemberNameEqualsClassName:
    active: false
  PackageNaming:
    packagePattern: '[a-z_]+(\.[a-z_][A-Za-z0-9_]*)*'

complexity:
  CyclomaticComplexMethod:
    active: false
  LargeClass:
    excludes:
      - '**/net/i2p/android/router/util/ConnectivityAndInternetAccess.kt'
  LongMethod:
    active: false
  LongParameterList:
    active: false
  NestedBlockDepth:
    active: false
  TooManyFunctions:
    active: false

exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: false

style:
  LoopWithTooManyJumpStatements:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
  UnusedPrivateFunction:
    allowedNames: '.*Preview$'
  UnusedPrivateProperty:
    active: false
    allowedNames: '_|ignored|expected|serialVersionUID'
