org.gradle.jvmargs=-Xmx6144m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.tooling.parallel=true
android.useAndroidX=true
android.enableJetifier=false
android.defaults.buildFeatures.resValues=false
android.defaults.buildFeatures.shaders=false
kotlin.native.disableCompilerDaemon = true
org.jetbrains.compose.experimental.jscanvas.enabled=true
org.jetbrains.compose.experimental.wasm.enabled=true
kotlin.native.ignoreDisabledTargets=true
