package org.michaelbel.moviemade

object Dependencies {
    const val KotlinCompilerExtensionVersion = "1.1.0-rc01"

    private const val KotlinVersion = "1.6.0"
    private const val KotlinCoroutinesVersion = "1.6.0"
    private const val KotlinSerializationVersion = "1.3.2"
    private const val ComposeVersion = "1.1.0-rc01"
    private const val ComposeCompilerVersion = "1.1.0-rc02"
    private const val MaterialVersion = "1.6.0-alpha02"
    private const val Material3Version = "1.0.0-alpha04"
    private const val MaterialComposeThemeAdapterVersion = "1.1.3"
    private const val HiltNavigationComposeVersion = "1.0.0-rc01"
    private const val LifecycleVersion = "2.4.0"
    private const val NavigationComposeVersion = "2.4.0-rc01"
    private const val PagingComposeVersion = "1.0.0-alpha14"
    private const val AccompanistVersion = "0.20.3"
    private const val CoilVersion = "1.4.0"
    private const val GradleVersion = "7.0.4"
    private const val NavigationPluginVersion = "2.4.0"
    private const val HiltVersion = "2.40.5"
    private const val GooglePlayServicesVersion = "4.3.10"
    private const val FirebaseCrashlyticsPluginVersion = "2.8.1"
    private const val FirebaseAppDistributionPluginVersion = "3.0.0"

    const val KotlinCoroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:$KotlinCoroutinesVersion"
    const val KotlinCoroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:$KotlinCoroutinesVersion"
    const val KotlinSerialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:$KotlinSerializationVersion"
    const val ComposeCompiler = "androidx.compose.compiler:compiler:$ComposeCompilerVersion"
    const val ComposeFoundation = "androidx.compose.foundation:foundation:$ComposeVersion"
    const val ComposeMaterial3 = "androidx.compose.material3:material3:$Material3Version"
    const val ComposeRuntime = "androidx.compose.runtime:runtime:$ComposeVersion"
    const val ComposeUi = "androidx.compose.ui:ui:$ComposeVersion"
    const val ComposeUiTooling = "androidx.compose.ui:ui-tooling:$ComposeVersion"
    const val HiltNavigationCompose = "androidx.hilt:hilt-navigation-compose:$HiltNavigationComposeVersion"
    const val LifecycleViewModelCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:$LifecycleVersion"
    const val NavigationCompose = "androidx.navigation:navigation-compose:$NavigationComposeVersion"
    const val PagingCompose = "androidx.paging:paging-compose:$PagingComposeVersion"
    const val AccompanistInsets = "com.google.accompanist:accompanist-insets:$AccompanistVersion"
    const val AccompanistSwipeRefresh = "com.google.accompanist:accompanist-swiperefresh:$AccompanistVersion"
    const val Material = "com.google.android.material:material:$MaterialVersion"
    const val MaterialComposeThemeAdapter = "com.google.android.material:compose-theme-adapter:$MaterialComposeThemeAdapterVersion"
    const val CoilCompose = "io.coil-kt:coil-compose:$CoilVersion"
    const val Gradle = "com.android.tools.build:gradle:$GradleVersion"
    const val KotlinPlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:$KotlinVersion"
    const val NavigationPlugin = "androidx.navigation:navigation-safe-args-gradle-plugin:$NavigationPluginVersion"
    const val HiltPlugin = "com.google.dagger:hilt-android-gradle-plugin:$HiltVersion"
    const val GooglePlayServicesPlugin = "com.google.gms:google-services:$GooglePlayServicesVersion"
    const val FirebaseCrashlyticsPlugin = "com.google.firebase:firebase-crashlytics-gradle:$FirebaseCrashlyticsPluginVersion"
    const val FirebaseAppDistributionPlugin = "com.google.firebase:firebase-appdistribution-gradle:$FirebaseAppDistributionPluginVersion"
}