name: Check PR

on:
#  push:
#    branches:
#      '**'
#    paths-ignore:
#      - '**.md'
#     - '.idea/**'
#      - '.github/**'
  pull_request:
    branches:
      '**'
    paths-ignore:
      - '**.md'
      - '.idea/**'
      - '.github/**'
  workflow_dispatch:
  
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
  KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

jobs:
  pr:
    runs-on: macos-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
          
      - name: Decode Keystore File
        id: decode_keystore_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore_release.jks'
          encodedString: ${{ secrets.KEYSTORE_FILE }}
          
      - name: Set Decoded File Location as Environment
        run: echo "KEYSTORE_FILE=${{ steps.decode_keystore_file.outputs.filePath }}" >> $GITHUB_ENV
          
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Lint
        run: ./gradlew lint

      - name: Detekt
        run: ./gradlew detekt

      - name: Spotless
        run: ./gradlew spotlessCheck

      - name: Test
        run: ./gradlew testDebug

      - name: Build
        run: ./gradlew compileDebugKotlin