name: Release

on:
#  push:
#    tags:
#    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      
#      - name: Build GMS Release Artifacts
#        run: ./gradlew androidApp:assembleGmsRelease

#      - name: Build HMS Release Artifacts
#        run: ./gradlew androidApp:assembleHmsRelease

#      - name: Build FOSS Release Artifacts
#        run: ./gradlew androidApp:assembleFossRelease
 
#      - name: Upload Artifacts to Outputs
#        uses: actions/upload-artifact@v2
#        with:
#          path: |
#            androidApp/build/outputs/apk
            
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,foo/*.txt,androidApp/build/outputs/apk/**/*.apk"
          artifactErrorsFailBuild: false
          generateReleaseNotes: true
